### ISSUE TITLE
Go & Ale

### ISSUE THREAD

**Issue by malisetti** [kode4food/ale#1]
I am just wondering if ale can be what clojure is to java, to Go. Also [Yaegi](http://github.com/containous/yaegi) is repl for golang, it would so cool to write lisp code using existing go libraries.

**Comment by kode4food** [comment]
Hi @mseshachalam!

At one point I did write a reflection/FFI system, but I scrapped it because I wasn't satisfied with the design. That said, yes, I will be introducing an FFI library at some point in the future. I just want to nail down the language design first.

In the meantime, you an fake it. Any Go function that matches the [Call](https://github.com/kode4food/ale/blob/master/data/function.go#L5) interface can be used internally by Ale. You'll just need to get it registered with a namespace after bootstrapping. That can be done by registering it with a namespace before you eval your Lisp code:

```go
myFunc := func(_ ...data.Value) data.Value {
  return data.String("hello")
}

manager := bootstrap.TopLevelManager()
bootstrap.Into(manager)
ns := manager.GetAnonymous()
ns.Declare("hello").Bind(data.Call(myFunc))
eval.String(ns, "(hello)")
```

This is described briefly in the [Embedding Ale](https://www.ale-lang.org/embedding/) article. Keep in mind that `data.Value` is essentially an alias for `fmt.Stringer`. So any value that implements that interface *should* be capable of being passed around by Ale. That may change in the future, as the FFI system may require relaxing the restriction.

Sorry for taking so long to get back to you on this.

**Comment by dc0d** [comment]
It would be useful that accessing Go packages/runtime could be turned on/off. That way Ale could be used as a safe embedded language for providing some imported/dynamic business logic without worrying for that code to perform unsafe operations - calling HTTP, accessing OS resources, and the like.

**Comment by kode4food** [comment]
Hi @dc0d, as of right now that's still the case. Ale cannot perform arbitrary reflection or invocation, instead requiring the developer to explicitly provide values into its environment that adhere to Ale's interfaces. As an FFI is built, the interface requirement will be relaxed, but the provisioning constraint will remain -- Ale will only be able to play with things you provide to it explicitly.

**Comment by kode4food** [comment]
I have created a branch called [ffi](https://github.com/kode4food/ale/tree/ffi) that is the starting point of an FFI. Still quite a lot to do (including cycle checks in the marshaling) but actively being worked on.

**Comment by kode4food** [comment]
I have merged the [ffi](https://github.com/kode4food/ale/tree/ffi) branch into [master](https://github.com/kode4food/ale/tree/master). Originally worried about having to change some of the basic interfaces of Ale to perform the work, but ended up not having to.

The interface is semi-functional at this point, but still quite fragile and incomplete.

For example, I haven't settled on a way to wrap `chan`. My though was that it should behave the way Ale [chan](https://www.ale-lang.org/docstring/chan/) works, exposing a sequence and emitter. Problem is that Ale manages the life-cycle of its channels.

**Comment by kode4food** [comment]
Another thing to note: Although I am handling cycles in type wrapping, the value marshaling doesn't yet perform cycle checks.

**Comment by kode4food** [comment]
Value wrapping now performs cycle checks (against Map, Slice, and Ptr) and returns an error when a cycle is encountered. Because Ale values are immutable and would otherwise tend to be based on persistent data structures, cycles (theoretically) can't occur in them, so allowing for cycles to be mapped from Go types is problematic.

I may revisit this decision in the future, but am going to wait and see how many people complain

**Comment by kode4food** [comment]
Hi everyone. I've recently posted an article about [Go and Ale](https://www.ale-lang.org/ffi/) that covers the FFI that is being built. It's getting pretty close to being usable. I don't anticipate any major changes to how it works. There are a few conversions still missing (complex numbers and unsafe pointers) but everything else should be ready to play with. If you don't mind, I'm going to close this issue.
